(function () {
    window.PERMISSION_SECTIONS = [
        "MASTERS",
        "ACCOUNT GROUP",
        "MISC. MASTERS",
        "MASTER DATA",
        "TRANSACTIONS",
        "SCREENING",
        "PRINTING",
        "BILL SECTION",
        "ACCOUNTING",
        "USER SECURITY",
        "UTILITIES"
    ];

    window.PAGE_PERMISSION_ITEMS = [
        { key: "PARTY_HTML", label: "Party Master", section: "MASTERS" },
        { key: "PRODUCT_HTML", label: "Product Master", section: "MASTERS" },
        { key: "BRAND_MASTER_HTML", label: "Brand Master", section: "MASTERS" },
        { key: "PARTY_WISE_BROKERAGE_RATE_SETUP_HTML", label: "Party Wise Brokerage Rate Setup", section: "MASTERS" },
        { key: "TRANSPORT_MASTER_HTML", label: "Transport Master", section: "MASTERS" },

        { key: "GROUP_MASTER_HTML", label: "Group Master", section: "ACCOUNT GROUP" },
        { key: "GROUP_TRANSFER_HTML", label: "Group Transfer", section: "ACCOUNT GROUP" },
        { key: "GROUP_SETUP_HTML", label: "Group Setup", section: "ACCOUNT GROUP" },

        { key: "STATE_HTML", label: "State Master", section: "MISC. MASTERS" },
        { key: "CITY_HTML", label: "City Master", section: "MISC. MASTERS" },
        { key: "DISTRICT_MASTER_HTML", label: "District Master", section: "MISC. MASTERS" },
        { key: "AREA_HTML", label: "Zone / Area Master", section: "MISC. MASTERS" },
        { key: "LINE_MASTER_HTML", label: "Line Master", section: "MISC. MASTERS" },
        { key: "LENGTH_MASTER_HTML", label: "Length Master", section: "MISC. MASTERS" },
        { key: "DEALS_IN_MASTER_HTML", label: "Deals In Master", section: "MISC. MASTERS" },
        { key: "TERM_TYPE_MASTER_HTML", label: "Term Type Master", section: "MISC. MASTERS" },
        { key: "COURIER_MASTER_HTML", label: "Courier Master", section: "MISC. MASTERS" },
        { key: "NARRATION_MASTER_HTML", label: "Narration Master", section: "MISC. MASTERS" },
        { key: "SKU_UNIT_MASTER_HTML", label: "SKU(Unit) Master", section: "MISC. MASTERS" },
        { key: "PARTY_TYPE_MASTER_HTML", label: "Party Type Master", section: "MISC. MASTERS" },
        { key: "PARTY_CATEGORY_MASTER_HTML", label: "Party Category Master", section: "MISC. MASTERS" },
        { key: "BANK_MASTER_HTML", label: "Bank Master", section: "MISC. MASTERS" },
        { key: "CONDITION_MASTER_HTML", label: "Condition Master", section: "MISC. MASTERS" },
        { key: "NOTE_MASTER_HTML", label: "Note Master", section: "MISC. MASTERS" },
        { key: "COMPANY_GROUP_MASTER_HTML", label: "Company Group Master", section: "MISC. MASTERS" },
        { key: "PRODUCT_TYPE_MASTER_HTML", label: "Product Type Master", section: "MISC. MASTERS" },
        { key: "PRODUCT_GROUP_MASTER_HTML", label: "Product Group Master", section: "MISC. MASTERS" },
        { key: "FORM_WISE_BOOK_SETUP_HTML", label: "Form Wise Book Setup", section: "MISC. MASTERS" },
        { key: "ADD_LESS_PARAMETER_HTML", label: "Add Less Parameter", section: "MISC. MASTERS" },
        { key: "DIVISION_MASTER_HTML", label: "Division Master", section: "MISC. MASTERS" },

        { key: "MASTER_DATA_ENTRY_HTML", label: "Master Data Entry", section: "MASTER DATA" },
        { key: "MASTER_DATA_PRINT_HTML", label: "Master Data Print", section: "MASTER DATA" },

        { key: "SALES_HTML", label: "Daily Sauda", section: "TRANSACTIONS" },
        { key: "LOADING_ENTRY_HTML", label: "Loading Entry", section: "TRANSACTIONS" },
        { key: "PAYMENT_ENTRY_HTML", label: "Payment Entry", section: "TRANSACTIONS" },
        { key: "SALES_REGISTRY_HTML", label: "Sauda Register", section: "TRANSACTIONS" },
        { key: "LOADING_REGISTER_HTML", label: "Loading Register", section: "TRANSACTIONS" },

        { key: "SCREENING_HTML", label: "Screening", section: "SCREENING" },
        { key: "PRINTING_HTML", label: "Printing", section: "PRINTING" },
        { key: "BILL_SECTION_HTML", label: "Bill Section", section: "BILL SECTION" },
        { key: "ACCOUNTING_HTML", label: "Accounting", section: "ACCOUNTING" },
        { key: "ACCOUNT_MASTER_HTML", label: "Account Master", section: "ACCOUNTING" },

        { key: "BACKUP_HTML", label: "Backup", section: "UTILITIES" },
        { key: "USER_MASTER_HTML", label: "User Master", section: "UTILITIES" },
        { key: "SMS_SETUP_HTML", label: "SMS Setup", section: "UTILITIES" },
        { key: "SEND_AUTO_SMS_HTML", label: "Send Auto SMS", section: "UTILITIES" },
        { key: "SEND_MANUAL_SMS_HTML", label: "Send Manual SMS", section: "UTILITIES" },
        { key: "SEND_OUTSTANDING_SMS_HTML", label: "Send Outstanding SMS", section: "UTILITIES" },
        { key: "ENVELOPE_PRINTING_HTML", label: "Envelope Printing", section: "UTILITIES" },
        { key: "REFRESH_PAYMENT_OUTSTANDING_LOADING_HTML", label: "Refresh Payment Outstanding (Loading)", section: "UTILITIES" },
        { key: "CHANGE_FIN_YR_DIV_HTML", label: "Change Fin. Yr (Div)", section: "UTILITIES" },
        { key: "ROLE_MASTER_HTML", label: "Role Master", section: "USER SECURITY" },
        { key: "USER_LOG_HTML", label: "User Log", section: "USER SECURITY" },
        { key: "COMPANY_DETAILS_HTML", label: "Company Details", section: "UTILITIES" },
        { key: "MERGE_ACCOUNT_HTML", label: "Merge Account", section: "UTILITIES" },
        { key: "MERGE_CITY_HTML", label: "Merge City", section: "UTILITIES" },
        { key: "MERGE_DELETE_DATA_HTML", label: "Merge & Delete Data", section: "UTILITIES" },
        { key: "FIND_TB_DIFFERENCE_HTML", label: "Find T.B. Difference", section: "UTILITIES" },
        { key: "RE_NUMBERING_HTML", label: "Re-Numbering", section: "UTILITIES" },
        { key: "MISSING_VOUCHER_SR_NO_HTML", label: "Missing Voucher Sr No", section: "UTILITIES" },
        { key: "RTGS_FORM_SETUP_HTML", label: "RTGS Form Setup", section: "UTILITIES" },
        { key: "UNIT_SETUP_HTML", label: "Unit Setup", section: "UTILITIES" },
        { key: "CONFIRM_HTML", label: "Confirm", section: "UTILITIES" },
        { key: "BF_BAL_FROM_PRV_YEAR_HTML", label: "B/F Bal from Prv Year", section: "UTILITIES" },
        { key: "CALCULATOR_HTML", label: "Calculator", section: "UTILITIES" },
        { key: "EXIT_SOFTWARE_HTML", label: "Exit Software", section: "UTILITIES" },
        { key: "SEARCH_HTML", label: "Search", section: "UTILITIES" }
    ];
})();
